export enum keysForArrayComponents {
    actionButton = "action-button",
    actionMenuItem = "action-menu-item",
    flexSkeletonLoader = 'flex-skeloader-loader',
    interchangeDisconnectionTab1 = 'interchange-disconnection-tabs-1',
    interchangeDisconnectionTab2 = 'interchange-disconnection-tabs-2',
    interchangeDisconnectionTabEmpty = 'interchange-disconnection-tabs-empty',
    menuText = 'menu-text',
    missionStatementMotionText = 'mission-statement-motion-text',
    motionTBodyCell = "motion-tbody-cell",
    motionTBodyRow = "motion-tbody-row",
    motionTrSkeleton = 'motion-tr-skeleton',
    motionTrActionSkeleton = 'motion-tr-action-skeleton',
    motionTrColumnSkeleton = 'motion-tr-column-skeleton',
    onboardingStep = 'onboarding-step',
    skeletonLoader = 'skeloader-loader',
    tableFooter = 'table-footer',
    tableColumn = 'table-column',
}