export enum notificationMesage {
    AccountActivated = "Account activated!",
    AccountVerified = "Your account has been verified!",
    AnErrorOccurred = "Oops! An error occuured",
    CantmoveToNextForm = "Can't move to the next form!",
    CantSubmitForm = "Oops! can't submit this form, try again!",
    emailRequired = "Email required",
    invalidEmailFormat = "Invalid Email format",
    mailSent = "Mail sent",
    Oops = "Oops!",
    SuccessfulAccountCreation = "Account creation successful!",
    SuccessfulBankCreation = "Bank creation successful!",
    SuccessfulLogin = "Login Successful!",
    SuccessfulRoleCreation = "Role creation successful!",
    SuccessfulSuperAdminCreation = "Super admin creation successful!",
    SuccessfulBankAdminCreation = "Bank admin creation successful!",
    TenantActivated = "Bank Activated successfully",
    TenantDeactivated = "Bank Deactivated successfully",
    offline = "You're currently offline!"
}