import { State } from "../models"

export const states: Readonly<State[]> = [
    { "id":"1", "name":"Abia State" },
    { "id":"2", "name":"Adamawa State" },
    { "id":"3", "name":"Akwa Ibom State" },
    { "id":"4", "name":"Anambra State" },
    { "id":"5", "name":"Bauchi State" },
    { "id": "6", "name":"Bayelsa State" },
    { "id": "7", "name":"Benue State" },
    { "id": "8", "name":"Borno State" },
    { "id": "9", "name":"Cross River State" },
    { "id": "10", "name":"Delta State" },
    { "id": "11", "name":"Ebonyi State" },
    { "id": "12", "name":"Edo State" },
    { "id": "13", "name":"Ekiti State" },
    { "id": "14", "name":"Enugu State" },
    { "id": "15", "name":"Gombe State" },
    { "id": "16", "name":"Imo State" },
    { "id": "17", "name":"Jigawa State" },
    { "id": "18", "name":"Kaduna State" },
    { "id": "19", "name":"Kano State" },
    { "id": "20", "name":"Katsina State" },
    { "id": "21", "name":"Kebbi State" },
    { "id": "22", "name":"Kogi State" },
    { "id": "23", "name":"Kwara State" },
    { "id": "24", "name":"Lagos State" },
    { "id": "25", "name":"Nasarawa State" },
    { "id": "26", "name":"Niger State" },
    { "id": "27", "name":"Ogun State" },
    { "id": "28", "name":"Ondo State" },
    { "id": "29", "name":"Osun State" },
    { "id": "30", "name":"Oyo State" },
    { "id": "31", "name":"Plateau State" },
    { "id": "32", "name":"Rivers State" },
    { "id": "33", "name":"Sokoto State" },
    { "id": "34", "name":"Taraba State" },
    { "id": "35", "name":"Yobe State" },
    { "id": "36", "name":"Zamfara State" }
  ]
  
  export const addresses:Readonly<string[]> = ["999c, Danmole Street, Off Idejo Street, Off Adeola Odeku Street, Victoria Island", "Plot 1261, Adeola Hopewell Street, Victoria Island", "2, Kofo Abayomi Street, Victoria Island", "Primose Towers, 17a, Tinubu Street", "Samuel Asabia House, 35 Marina", "635, Akin Adesola Street, Victoria Island", "Stallion Plaza, 36 Marinas", "57 Marina", "Plot 84, Ajose Adeogun Street, Victoria Island"] 