export enum StatsName {
    createdBanks = "Created Banks",
    tenantAdminUser = "Bank Admin User",
    iSWAdminUser = "ISW Admin User",
    atmInSupervisor = "ATM In-Supervisor",
    atmCount = "ATM Count",
    atmLowCashLevel = "ATM Low Cash Level",
    atmInService = "ATM In Service",
    atmOutService = "ATM Out Service",
    atmInCashJam = "ATM In Cash-Jam",
    atmCassetteErrors = "ATM Caseette Errors",
    transactionAmount = "Transaction Amount",
    transactionCount = "Transaction Count",
    balanceEnquiry = "Balance Enquiry",
    pinChange = "Pin Change",
    cashWithdrawal = "Cash Withdrawal",
    quicktellerAirtime = "Quickteller Airtime",
    quicktellerBill = "Quickteller Bill",
    paycodeWithdrawal = "Paycode Withdrawal",
    totalInService = "Total in Service",
    totalOutOfService = "Total Out of Service"
}